let shopItemsData = [
	{
		id: "q8e670560b934c2fa139bcb8e8eda303",
		section: "bakery",
		type: "bagel",
		name: "Plain Bagel",
		desc: "Made Using Plain Bread Flour And Does Not Have Any Toppings",
		img: "img/bakery/bagel/plain-bagel.webp",
		price: 3,		
	},
	{
		id: "w53b85ea8cd2409da2f5ffc3ecd6777c",
		section: "bakery",
		type: "bagel",
		name: "Everything Bagel",
		desc: "Combination Of Sesame Seeds, Poppy Seeds, Salt And Onion Toppings",
		img: "img/bakery/bagel/everything-bagel.webp",
		price: 4,		
	},
	{
		id: "e1357140a2b748cba1d97f1a64a0d71e",
		section: "bakery",
		type: "bagel",
		name: "Cinnamon Raisin Bagel",
		desc: "Bagels With The Sweetness Of Rasins Paired With A Subtle Cinnamon Spice",
		img: "img/bakery/bagel/cinnamon-raisin-bagel.webp",
		price: 4,		
	},
	{
		id: "ra25f1d1153f4070b612c59eb4777af8",
		section: "bakery",
		type: "bagel",
		name: "Salt Bagel",
		desc: "Plain Bagel Topped With Salt Before Baking",
		img: "img/bakery/bagel/salt-bagel.webp",
		price: 3,		
	},
	{
		id: "d4faecbb4e4c4e1e84e6356a6822ce28",
		section: "bakery",
		type: "bagel",
		name: "Egg Bagel",
		desc: "Made With Egg Yolks In Dough Mixture Resulting In A Soft Texture And Sweet Flavour",
		img: "img/bakery/bagel/egg-bagel.webp",
		price: 4,		
	},
	{
		id: "t36bb9c4b40346a083115b19191ede60",
		section: "bakery",
		type: "bagel",
		name: "Sesame Bagel",
		desc: "Crunchy And Delicious With A Warm Nutty Flavour",
		img: "img/bakery/bagel/sesame-bagel.webp",
		price: 4,		
	},
	{
		id: "y07d633d332a472cacffeccf6bbb6c76",
		section: "bakery",
		type: "bagel",
		name: "Poppy Seed Bagel",
		desc: "Both Soft And Crunchy With A Fruity And Nutty Flavour",
		img: "img/bakery/bagel/poppy-bagel.webp",
		price: 5,		
	},
	{
		id: "u17efbc762c94ed8817e409cd2b52106",
		section: "bakery",
		type: "bagel",
		name: "Garlic Bagel",
		desc: "Rich Aroma Derived From Cooked Garlic Resulting In A Rich Sweet and Savoury Flaour",
		img: "img/bakery/bagel/garlic-bagel.webp",
		price: 4,		
	},
	{
		id: "ia620947e2aa4b51ab24c44f0190980f",
		section: "bakery",
		type: "bagel",
		name: "Whole Wheat Bagel",
		desc: "Fibre And Mineral Rich Bagel",
		img: "img/bakery/bagel/whole-wheat-bagel.webp",
		price: 3,		
	},
	{
		id: "o9ffafccc7e54875bc54e81ff89dfcc6",
		section: "bakery",
		type: "bagel",
		name: "Pumpernickel Bagel",
		desc: "Made Using Sourdough And Coarsley Ground WholeRye Grains",
		img: "img/bakery/bagel/pumpernickel-bagel.webp",
		price: 5,		
	},
	{
		id: "ea6d5c183b774e33b94cb3ea6d8824bb",
		section: "bakery",
		type: "bagel",
		name: "Rainbow Bagel",
		desc: "Stuffed With Cotton Candy And Cream Cheesed Flavoured With Rainbow Sprinckle Cake",
		img: "img/bakery/bagel/rainbow-bagel.webp",
		price: 6,		
	},
	{
		id: "f6f232edd6ce4f4e84c4ac41c880132c",
		section: "bakery",
		type: "bagel",
		name: "Blueberry Bagel",
		desc: "Slightly Bluish-Purple Tint Absorbed From Infused Blueberries During Mixing",
		img: "img/bakery/bagel/blueberry-bagel.webp",
		price: 6,		
	},
																														// Bread
	{
		id: "p34e7903e2de4c1b9852cc5cd926f665",
		section: "bakery",
		type: "bread",
		name: "White Bread",
		desc: "Processed White Bread",
		img: "img/bakery/bread/white-bread.webp",
		price: 12,
	},
	{
		id: "ad0d1178b5894a9abd8049da63c93d12",
		section: "bakery",
		type: "bread",
		name: "Wheat Bread",
		desc: "Wheat Flour Bread",
		img: "img/bakery/bread/wheat-bread.webp",
		price: 15,
	},
	{
		id: "s1b54a14ed004c22947848857de9388d",
		section: "bakery",
		type: "bread",
		name: "Whole Wheat Bread",
		desc: "Made From Multiple Refined and Processed Grains",
		img: "img/bakery/bread/whole-wheat-bread.webp",
		price: 19,
	},
	{
		id: "a1aff1c2405d4e0cbf88b09980c17577",
		section: "bakery",
		type: "bread",
		name: "Multigrain Bread",
		desc: "Made From Multiple Refined and Processed Grains",
		img: "img/bakery/bread/multigrain-bread.webp",
		price: 16,
	},
	{
		id: "eef7bdad7b1c4fb7802e850096ece3d4",
		section: "bakery",
		type: "bread",
		name: "Whole Grain Bread",
		desc: "Made From Unprocessed Wheat, Whole Barley and Brown Rice",
		img: "img/bakery/bread/whole-grain-bread.webp",
		price: 16,
	},
	{
		id: "d446c25bbe004cb1a8b93307a49caab9",
		section: "bakery",
		type: "bread",
		name: "Sprouted Grain Bread",
		desc: "Made From Grains Exposed To Warm, Moist Conditions",
		img: "img/bakery/bread/sprouted-grain-bread.webp",
		price: 25,
	},
	{
		id: "fd89c5a456164aa985e479bca2a84900",
		section: "bakery",
		type: "bread",
		name: "Sourdough Bread",
		desc: "Made From Fermentation",
		img: "img/bakery/bread/sourdough-bread.webp",
		price: 28,
	},
	{
		id: "f69f8b0b4a79478c95c444b77835b4bf",
		section: "bakery",
		type: "bread",
		name: "Rye Bread",
		desc: "Made From Rye Grain",
		img: "img/bakery/bread/rye-bread.webp",
		price: 30,
	},
	{
		id: "gd9e9e115f224c068a9eb5af532587b1",
		section: "bakery",
		type: "bread",
		name: "Pumpernickel Bread",
		desc: "Made From Coarsley ground Rye Grain And Fermented With Sourdough Starter",
		img: "img/bakery/bread/pumpernickel-bread.webp",
		price: 33,
	},
	{
		id: "a76c3de176a7489d8afd29b2e8909592",
		section: "bakery",
		type: "bread",
		name: "Brioche",
		desc: "Very Rich Bread Made With Additions Of Egg, Milk and Butter",
		img: "img/bakery/bread/brioche-bread.webp",
		price: 35,
	},
	{
		id: "c231cd27c4e64a1aab6abd0019202233",
		section: "bakery",
		type: "bread",
		name: "Challah",
		desc: "Very Rich Bread Made With Additions Of Egg, Milk and Oil",
		img: "img/bakery/bread/challah-bread.webp",
		price: 35,
	},
	{
		id: "h4bce446f36143a794198f16cc9bbc84",
		section: "bakery",
		type: "bread",
		name: "Flatbread",
		desc: "Made From A Simple Mixture Of Flour, Water, and Salt",
		img: "img/bakery/bread/flatbread.webp",
		price: 30,
	},
	{
		id: "jf84217ca699475292a3a5c994c82e93",
		section: "bakery",
		type: "bread",
		name: "Cornbread",
		desc: "Made From Cornmeal With A Cake-Like Texture",
		img: "img/bakery/bread/cornbread.webp",
		price: 25,
	},
	{
		id: "baa520ff5aa844099c95ea21f16b871a",
		section: "bakery",
		type: "bread",
		name: "Baguette",
		desc: "French Bread With Crunchy Exterior",
		img: "img/bakery/bread/baguette.webp",
		price: 23,
	},
	{
		id: "adc195e7ff064c38a2c6d6eac87bbd5f",
		section: "bakery",
		type: "bread",
		name: "Ciabatta",
		desc: "italian Bread With Similar Texture To A Baguette",
		img: "img/bakery/bread/ciabatta.webp",
		price: 25,
	},
	{
		id: "j69953c9a50e4e1b8ef4b7a483b89f0a",
		section: "bakery",
		type: "bread",
		name: "Soda Bread",
		desc: "Made With Baking Soda, Nuts, and Seeds.",
		img: "img/bakery/bread/soda-bread.webp",
		price: 26,
	},
																														// Cake
	{
		id: "aa2bd5d2e4934e79a5376c458b61fc2f",
		section: "bakery",
		type: "cake",
		name: "Butter Cake",
		desc: "Buttermilk-Raspberry Cake Baked And Presented As A Layer Cake",
		img: "img/bakery/cake/butter-cake.webp",
		price: 120,
	},																							
	{
		id: "kaa0aaf403dc418288eaeebaad45435a",
		section: "bakery",
		type: "cake",
		name: "Pound Cake",
		desc: "Lemon-Olive Pound Cake With Poppy Seeds",
		img: "img/bakery/cake/pound-cake.webp",
		price: 90,
	},
	{
		id: "l232567726eb49d4a7a9e2f8d1a6f2d3",
		section: "bakery",
		type: "cake",
		name: "Sponge Cake",
		desc: "Sponge Cake Filled With Meyer Lemon Curd, Served With Lavender Cream",
		img: "img/bakery/cake/sponge-cake.webp",
		price: 109,
	},
	{
		id: "z61a8c45dc4040e4a086c6c6cc63f5b8",
		section: "bakery",
		type: "cake",
		name: "Biscuit Cake",
		desc: "Made With A Light Batter That Holds Its Shape After Mixing",
		img: "img/bakery/cake/biscuit-cake.webp",
		price: 110,
	},
	{
		id: "x9f0ceb591b64d99b5513c4ac814dff6",
		section: "bakery",
		type: "cake",
		name: "Angel Food Cake",
		desc: "Fluffy, Sweet and Light Cake Served With Fresh Whipped Cream And Seasonal Berries",
		img: "img/bakery/cake/angel-food-cake.webp",
		price: 150,
	},
	{
		id: "c6527a74ec5b4f5ebcf0bff68cfda5c6",
		section: "bakery",
		type: "cake",
		name: "Baked Flourless Cake",
		desc: "Naturally Gluten Free Flourless Chocolate  Cake",
		img: "img/bakery/cake/baked-flourless-cake.webp",
		price: 80,
	},
	{
		id: "v45e3a1a520245de8c1e3c661677a2f1",
		section: "bakery",
		type: "cake",
		name: "Unbked Flourless Cake",
		desc: "BlueBerry-Lemon Icebox Cake",
		img: "img/bakery/cake/unbaked-flourless-cake.webp",
		price: 105,
	},
	{
		id: "b25091ac5a7840618468833fda87b5fa",
		section: "bakery",
		type: "cake",
		name: "Carrot Cake",
		desc: "Classic Carrot-Coconut Cake With A Healthy Dose Of Ginger, Cinnamon, and Cream Cheese Frosting Sprinkled with Coconut Flakes",
		img: "img/bakery/cake/carrot-cake.webp",
		price: 180,
	},
	{
		id: "bfd908c510ff4303aec740bd76c95541",
		section: "bakery",
		type: "cake",
		name: "Red Velvet Cake",
		desc: "Tender, Chocolate-y, Crumb Free Texture Topped With Smooth Cream Cheese Frosting",
		img: "img/bakery/cake/red-velvet-cake.webp",
		price: 210,
	},
																													// Muffin
	{
		id: "n4d6e0411ffb40fba3d56e678c37746e",
		section: "bakery",
		type: "muffin",
		name: "Healthy Pumpkin Muffin",
		desc: "Pumkin Spice latte In Muffin Form Topped With Some Hazlenuts",
		img: "img/bakery/muffin/pumpkin-muffin.webp",
		price: 5,
	},
	{
		id: "m7736bc39e46411e915975f0bac8aa72",
		section: "bakery",
		type: "muffin",
		name: "Keto Blueberry Muffin",
		desc: "these Muffins Have Protein, Fruit, And Are Sugar Free",
		img: "img/bakery/muffin/blueberry-muffin.webp",
		price: 6,
	},
	{
		id: "b51bf6dcdc484d3d944d5efdbd33140a",
		section: "bakery",
		type: "muffin",
		name: "Chocolate Chip Muffin",
		desc: "Perfect Crispy Top And Fluffy Center",
		img: "img/bakery/muffin/choc-chip-muffin.webp",
		price: 6,
	},
	{
		id: "d428f734ef984fcd944ab73a57e79a96",
		section: "bakery",
		type: "muffin",
		name: "Pecan Pie Muffin",
		desc: "Perfect Crispy Top And Fluffy Center",
		img: "img/bakery/muffin/pecan-pie-muffin.webp",
		price: 6,
	},
	{
		id: "qfee10ce97124eb487fedb6ae11a537b",
		section: "bakery",
		type: "muffin",
		name: "Banana Nut Muffin",
		desc: "Light And Moist, Full Of Toasted Walnuts",
		img: "img/bakery/muffin/banana-nut-muffin.webp",
		price: 6,
	},
	{
		id: "wd981f7fd24a4a42a79f577d8727c169",
		section: "bakery",
		type: "muffin",
		name: "Cauliflower Breakfast Muffin",
		desc: "No Carbs But Lots Of Cheese And Ham",
		img: "img/bakery/muffin/cauliflower-breakfast-muffin.webp",
		price: 9,
	},
	{
		id: "fa043261becf485882df6f99bf4b52ef",
		section: "bakery",
		type: "muffin",
		name: "Hash Brown Cup Muffin",
		desc: "Full On The Go Breakfast Muffin",
		img: "img/bakery/muffin/hash-brown-muffin.webp",
		price: 10,
	},
	{
		id: "bab6c85c5e484ab2ac9ee84fe79da7f9",
		section: "bakery",
		type: "muffin",
		name: "Deep Dish Pizza Muffin",
		desc: "A Deep Dish Pizza A Muffin",
		img: "img/bakery/muffin/deep-dish-muffin.webp",
		price: 12,
	},
	{
		id: "fabdeec115ae425ea433dc91a57addfc",
		section: "bakery",
		type: "muffin",
		name: "Mocha Chip Muffins",
		desc: "Sweet Chocolate Chips With A Little Espresso For An Extra Boost",
		img: "img/bakery/muffin/mocha-chip-muffin.webp",
		price: 11,
	},
	{
		id: "d729b8c08a1f4c2aa3d39f12a9e14913",
		section: "bakery",
		type: "pastry",
		name: "Spinach Puffs",
		desc: "Filled With A Mixture Of Sauteed Onion, Garlic, Spinach, And Cream Cheese",
		img: "img/bakery/pastry/spinach-puffs.webp",
		price: 15,
	},
	{
		id: "ec84c1d9b1144431a7aa1656c8923818",
		section: "bakery",
		type: "pastry",
		name: "Mini Bacon Asparagus Quiches",
		desc: "Classic Quiche With Bacon and Aparagus",
		img: "img/bakery/pastry/bacon-asparagus-quiche.webp",
		price: 24,
	},
	{
		id: "f3f3446a2d474db78b210dea00d570c0",
		section: "bakery",
		type: "pastry",
		name: "Cheese Straws",
		desc: "Crunchy, Flacky and Cheesy Straws",
		img: "img/bakery/pastry/cheese-straw.webp",
		price: 18,
	},
	{
		id: "rb705bbad703463bb21175cb49ea9fd8",
		section: "bakery",
		type: "pastry",
		name: "Giant Danish Tart",
		desc: "Massive Danish Tart topped With Raspberry Jam",
		img: "img/bakery/pastry/fruit-danish.webp",
		price: 26,
	},
	{
		id: "a0fac9ec46564ecbb0b7288d4d93025f",
		section: "bakery",
		type: "pastry",
		name: "Broccoli Cheddar Hand Pies",
		desc: "Made With Sauteed Brocoli Engulfed by Creamy Cheddar Cheese",
		img: "img/bakery/pastry/broccoli-cheddar-pie.webp",
		price: 18,
	},
	{
		id: "t0ec0a3d70944740b879fe10e2ba66cc",
		section: "bakery",
		type: "pastry",
		name: "Mushroom and Burrata Tart",
		desc: "Delicious Mixture of Wild Mushroom and Burrata",
		img: "img/bakery/pastry/mushroom-tart.webp",
		price: 30,
	},
	{
		id: "yd659228f8a94cf39e7647ecc4cdacbf",
		section: "bakery",
		type: "pastry",
		name: "Cherry Puff Pastry Pies",
		desc: "Made With Oarganically Grown Cherries",
		img: "img/bakery/pastry/cherry-pie.webp",
		price: 28,
	},
	{
		id: "u5e2a54764cf41a3a068ea606d0983b5",
		section: "bakery",
		type: "pastry",
		name: "Asparagus And Chive Tart",
		desc: "Fresh Asparagus In A Buttery Crust",
		img: "img/bakery/pastry/asparagus-chive-tart.webp",
		price: 25,
	},
	{
		id: "ia224f1ce561431b96a24bd7babe47e0",
		section: "butchery",
		type: "beef",
		name: "Hanger Steak",
		desc: "Marinating Optional, Remove Center Membrane Before Cooking",
		img: "img/butchery/beef/hanger-steak.webp",
		price: 100,
	},
	{
		id: "o5ed3e0972634e479ea4772021c85a03",
		section: "butchery",
		type: "beef",
		name: "Top Blade/Flat Iron Steak",
		desc: "Marinating Recommended, Well Marbled But Fairly Lean",
		img: "img/butchery/beef/top-blade-steak.webp",
		price: 90,
	},
	{
		id: "pb628a22229a415e8f401b5248cd4489",
		section: "butchery",
		type: "beef",
		name: "Tri Tip Steak",
		desc: "Marinating Recommended, Thick And Lean",
		img: "img/butchery/beef/tri-tip-steak.webp",
		price: 80,
	},
	{
		id: "c47a4401adc043709431d20e6860c289",
		section: "butchery",
		type: "beef",
		name: "Rib-Eye Steak",
		desc: "Marinating Optional, Well Marbled",
		img: "img/butchery/beef/rib-eye-steak.webp",
		price: 150,
	},
	{
		id: "c9660ba4b8104724967538be1172390f",
		section: "butchery",
		type: "beef",
		name: "Sirloin",
		desc: "Marinating Recommended, Extra Lean",
		img: "img/butchery/beef/sirloin-steak.webp",
		price: 120,
	},
	{
		id: "d444569acb924925882c55bfc78e2c98",
		section: "butchery",
		type: "beef",
		name: "Skirt Steak",
		desc: "Marinating Optional, Long and Thin, Cooks Quickly",
		img: "img/butchery/beef/skirt-steak.webp",
		price: 110,
	},
	{
		id: "a307e41fb6b74c8c897d61b90fa34799",
		section: "butchery",
		type: "beef",
		name: "T-Bone Steak",
		desc: "Marinating Not Necessary",
		img: "img/butchery/beef/t-bone-steak.webp",
		price: 160,
	},
	{
		id: "f2494a991dfa4c58bf04dd817bc889bb",
		section: "butchery",
		type: "beef",
		name: "Strip Steak",
		desc: "Marinating Optional, Lean But Tender",
		img: "img/butchery/beef/strip-steak.webp",
		price: 130,
	},
	{
		id: "s85369a398614aab8024297739750133",
		section: "butchery",
		type: "beef",
		name: "Fillet Mignon/Tenderloin Steak",
		desc: "Marinating Not Necessary, Tie Twine Around Side For Even Cooking",
		img: "img/butchery/beef/fillet-mignon.webp",
		price: 140,
	},
	{
		id: "c1fe369e6a124d9c913555ce04a0670f",
		section: "butchery",
		type: "beef",
		name: "Flank Steak",
		desc: "Marinating Recommended, Lean, Can Be Tough, Best Thinly Sliced",
		img: "img/butchery/beef/flank-steak.webp",
		price: 70,
	},
	{
		id: "f2508ea138fe48f1a91333e9975632e2",
		section: "butchery",
		type: "poultry",
		name: "Full Chicken",
		desc: "Free Range Full Chicken",
		img: "img/butchery/poultry/full-chicken.webp",
		price: 70,
	},
	{
		id: "g61d589f68a2496fb4848ceebc368b91",
		section: "butchery",
		type: "poultry",
		name: "Chicken Breasts",
		desc: "Boneless and Skinless Chicken Breast",
		img: "img/butchery/poultry/chicken-breast.webp",
		price: 30,
	},
	{
		id: "h8130db4850849b48926c35175d005f6",
		section: "butchery",
		type: "poultry",
		name: "Chicken Drumsticks",
		desc: "Boned Freerange Drumstick",
		img: "img/butchery/poultry/chicken-drumstick.webp",
		price: 25,
	},
	{
		id: "jad14a9695934eae93c639132340b997",
		section: "butchery",
		type: "poultry",
		name: "Chicken Wings",
		desc: "Freerange Drumlettes And Mid-Joint Wings",
		img: "img/butchery/poultry/chicken-wing.webp",
		price: 20,
	},
	{
		id: "b99a13b73b8c4d6eae55225fac973e73",
		section: "butchery",
		type: "poultry",
		name: "Chicken Ham",
		desc: "Lower Part Of The Chicken Leg",
		img: "img/butchery/poultry/chicken-ham.webp",
		price: 30,
	},
	{
		id: "fa62a1872b124435b517cdb0ef2ee484",
		section: "butchery",
		type: "poultry",
		name: "Chicken Thigh",
		desc: "Upper Part Of The Chicken Leg",
		img: "img/butchery/poultry/chicken-thigh.webp",
		price: 32,
	},
	{
		id: "k480121a133a4f58b901d160cd2d8192",
		section: "butchery",
		type: "poultry",
		name: "Chicken Liver",
		desc: "Livers From Free Range Chickens",
		img: "img/butchery/poultry/chicken-liver.webp",
		price: 15,
	},
	{
		id: "l98466c22a724ca28c478c787bb20f9f",
		section: "butchery",
		type: "poultry",
		name: "Chicken Gizzards",
		desc: "Gizzards From Free Range Chickens",
		img: "img/butchery/poultry/chicken-gizzard.webp",
		price: 16,
	},
	{
		id: "z5e478533286442884c7d569f2c7db83",
		section: "butchery",
		type: "lamb",
		name: "Lamb Neck",
		desc: "Perfect for Kebabs Or Stews",
		img: "img/butchery/lamb/lamb-neck.webp",
		price: 140,
	},
	{
		id: "x00ceec39f9642db9179e1bc47d6de8e",
		section: "butchery",
		type: "lamb",
		name: "Lamb Neck Fillet",
		desc: "Tough Cut Perfect For Slow Cooking",
		img: "img/butchery/lamb/lamb-neck-fillet.webp",
		price: 130,
	},
	{
		id: "c05b36c8f37d4b20881f7c01fb92d903",
		section: "butchery",
		type: "lamb",
		name: "Lamb Rack",
		desc: "Highly Tender And Delicious Cut of Meat",
		img: "img/butchery/lamb/lamb-rack.webp",
		price: 230,
	},
	{
		id: "d4c908c12b844c24b7b67dc8b52983fe",
		section: "butchery",
		type: "lamb",
		name: "Shoulder of Lamb",
		desc: "Very Lean With Some Good Marbling, And Quite Flavourfull",
		img: "img/butchery/lamb/lamb-shoulder.webp",
		price: 180,
	},
	{
		id: "bc00ef3cd6944279bb473833bb1bfac6",
		section: "butchery",
		type: "lamb",
		name: "Lamb Chop",
		desc: "Tender and Flavourfull",
		img: "img/butchery/lamb/lamb-chop.webp",
		price: 140,
	},
	{
		id: "n4d4b0cabcaf4b9f8e33f01f19ed917e",
		section: "butchery",
		type: "lamb",
		name: "Lamb Rump",
		desc: "Cut From Back of The Lamb. Lean, Tender And Full Of Flavour",
		img: "img/butchery/lamb/lamb-rump.webp",
		price: 170,
	},
	{
		id: "m74c02d1bbd34d30b308257b1d692cc0",
		section: "butchery",
		type: "lamb",
		name: "Lamb Loin Chop",
		desc: "Lean Tender And Deliciously Flavourfull ",
		img: "img/butchery/lamb/lamb-loin-chop.webp",
		price: 150,
	},
	{
		id: "qedc5b1ecdc547ccb2ff1187f45176ef",
		section: "butchery",
		type: "lamb",
		name: "Leg of Lamb",
		desc: "Most Tender Cut Of Meat On A Lamb",
		img: "img/butchery/lamb/leg-of-lamb.webp",
		price: 250,
	},
	{
		id: "j97e653938364f0bb21035d8ec571997",
		section: "butchery",
		type: "lamb",
		name: "Lamb Shank",
		desc: "Lean Cut But Still Big On Flavour. Contains Large Amounts Of Collagen",
		img: "img/butchery/lamb/lamb-shank.webp",
		price: 200,
	},
	{
		id: "l175a7dc20224eeab0271341d8e50428",
		section: "butchery",
		type: "pork",
		name: "Pork Belly",
		desc: "Long Cut of Pork Belly With Plenty Of Fat Worked Into The Meat",
		img: "img/butchery/pork/pork-belly.webp",
		price: 220,
	},
	{
		id: "s553e459cc304fc98c9b862a814bc041",
		section: "butchery",
		type: "pork",
		name: "Pork Loin Chops",
		desc: "Thick, Boned Cut That Is Juice And Most Flavourfull",
		img: "img/butchery/pork/pork-loin-chops.webp",
		price: 150,
	},
	{
		id: "p23ab679db204be6833f73608edeb819",
		section: "butchery",
		type: "pork",
		name: "Pork Shoulder Chops",
		desc: "Fattier and Tougher Than Other Chop Cuts",
		img: "img/butchery/pork/pork-shoulder-chops.webp",
		price: 110,
	},
	{
		id: "d35047211fe54927bb5e48f040f072d7",
		section: "butchery",
		type: "pork",
		name: "Pork Loin",
		desc: "Leanest And Most Tender Pork Cut",
		img: "img/butchery/pork/pork-loin.webp",
		price: 180,
	},
	{
		id: "eb1d65da581f4561918c8379ef6459bd",
		section: "butchery",
		type: "pork",
		name: "Pork Roast",
		desc: "Lean Moist And Flavourfull",
		img: "img/butchery/pork/pork-roast.webp",
		price: 200,
	},
	{
		id: "a45765febd5b48a182464f34b55d324b",
		section: "butchery",
		type: "pork",
		name: "Pork Loin Ribs",
		desc: "Meatiest And fattiest Pork Ribs",
		img: "img/butchery/pork/pork-loin-ribs.webp",
		price: 190,
	},
	{
		id: "ub481ac6ee85445aa6582c97594c04de",
		section: "butchery",
		type: "pork",
		name: "Pork Spare Ribs",
		desc: "Least Meaty Pork Ribs",
		img: "img/butchery/pork/pork-spare-ribs.webp",
		price: 210,
	},
	{
		id: "e4e1a67339454f3ca5c5a9b1d7bfb211",
		section: "butchery",
		type: "pork",
		name: "Pork Tenderloin",
		desc: "Lean, Tender, Boneless",
		img: "img/butchery/pork/pork-tenderloin.webp",
		price: 200,
	},
	{
		id: "v4d86ac9993b426a9a05e4c451d7d5b1",
		section: "butchery",
		type: "pork",
		name: "Pork Shank",
		desc: "Great Flavourfull Cut For Broths",
		img: "img/butchery/pork/pork-shank.webp",
		price: 140,
	},
	{
		id: "c677bb3e8c32479bbaaf6c9347e96937",
		section: "butchery",
		type: "pork",
		name: "Pork Trotters",
		desc: "Tough Cut of Meaty Flavour",
		img: "img/butchery/pork/pork-trotters.webp",
		price: 100,
	},
	{
		id: "p90fb9458564486da7c7302d91dbb7b7",
		section: "dairy",
		type: "butter",
		name: "Unsalted Butter",
		desc: "Mildly Sweet Butter, Best For Baking",
		img: "img/dairy/butter/unsalted-butter.webp",
		price: 26,
	},
	{
		id: "a48cb15b5cf9496883e109855b8dabf9",
		section: "dairy",
		type: "butter",
		name: "Salted Butter",
		desc: "Extra Salt Helps Flaavours In Recipes",
		img: "img/dairy/butter/salted-butter.webp",
		price: 28,
	},
	{
		id: "n67a05249b034f9baf4755499c638588",
		section: "dairy",
		type: "butter",
		name: "Sweet Cream Butter",
		desc: "Butter Made From Sweet Cream",
		img: "img/dairy/butter/sweet-cream-butter.webp",
		price: 30,
	},
	{
		id: "febbb8f177d547af9b23ca44d5302850",
		section: "dairy",
		type: "butter",
		name: "Cultured Butter",
		desc: "Hand Crafted Artisan Butter",
		img: "img/dairy/butter/cultured-butter.webp",
		price: 35,
	},
	{
		id: "p9efda3a82044fba9965abbbf5232bef",
		section: "dairy",
		type: "butter",
		name: "Ghee",
		desc: "Higher Smoke Point And A RIcher, Fuller Flavour",
		img: "img/dairy/butter/ghee.webp",
		price: 38,
	},
	{
		id: "b9698491c6fa4894a29fbf2a7c5580df",
		section: "dairy",
		type: "butter",
		name: "Organic Butter",
		desc: "Comes From Cows Only Given Food That Was Pesticide and Fertilizer Free",
		img: "img/dairy/butter/organic-butter.webp",
		price: 35,
	},
	{
		id: "d7b17e4b5fa84f12ae0f77bb400f512b",
		section: "dairy",
		type: "butter",
		name: "Butter Spread/Margarine",
		desc: "Mixture Of Butter And Vegetable Oil",
		img: "img/dairy/butter/margarine.webp",
		price: 25,
	},
	{
		id: "yab0e7682c2e48c48af25d69687cf959",
		section: "dairy",
		type: "butter",
		name: "Whipped Butter",
		desc: "Softened Butter With Fluffy And Airy Texture",
		img: "img/dairy/butter/whipped-butter.webp",
		price: 25,
	},
	{
		id: "p019ff931b9b4d27be732ed2e41f977a",
		section: "dairy",
		type: "butter",
		name: "Goat Butter",
		desc: "Butter Made From Goat Milk",
		img: "img/dairy/butter/goat-butter.webp",
		price: 30,
	},
	{
		id: "c177f56154cd4c4180f11188583e5523",
		section: "dairy",
		type: "cheese",
		name: "Roquefort",
		desc: "Has A Moist Crumbly Paste And Sharp, Sweet And Nutty Flavour",
		img: "img/dairy/cheese/roquefort.webp",
		price: 36,
	},
	{
		id: "la897fb4aa3b43d7bf29a9590edad392",
		section: "dairy",
		type: "cheese",
		name: "Camembert",
		desc: "Rich, Buttery, And Spreadable. Has A Mild, Mushroomy Aroma",
		img: "img/dairy/cheese/camembert.webp",
		price: 40,
	},
	{
		id: "d5388650c7cb48e7b36ee359547a7e01",
		section: "dairy",
		type: "cheese",
		name: "Feta",
		desc: "Tandy And Moist, Crumbly And Moderately Creamy",
		img: "img/dairy/cheese/feta.webp",
		price: 34,
	},
	{
		id: "fec693c86e4445f1a8fd265f92a60a28",
		section: "dairy",
		type: "cheese",
		name: "Mozzarella",
		desc: "Fresh And Dairy Rich. Great texture And Creamy Flavour",
		img: "img/dairy/cheese/mozzarella.webp",
		price: 39,
	},
	{
		id: "d774dd02b06048b6b09c18c76272e537",
		section: "dairy",
		type: "cheese",
		name: "Cheddar",
		desc: "Dry And Crumbly In Texture, With A Deep, Tangy, Nutty Flavour",
		img: "img/dairy/cheese/cheddar.webp",
		price: 40,
	},
	{
		id: "ca429ff57ac8430994de2a8181c18b3f",
		section: "dairy",
		type: "cheese",
		name: "Parmesan",
		desc: "Hard, Dry Crumbly Cheese That has A Great Crunch And Deep Caramel-y, Nutty Flavours",
		img: "img/dairy/cheese/parmesan.webp",
		price: 42,
	},
	{
		id: "ff0fe3606fd743bd8fd82c785da39e6b",
		section: "dairy",
		type: "cheese",
		name: "Danish Blue",
		desc: "Savoury And Sweet",
		img: "img/dairy/cheese/danish-blue.webp",
		price: 38,
	},
	{
		id: "pd76265f39c74b6eaecc68bd0c46d908",
		section: "dairy",
		type: "cheese",
		name: "Brie",
		desc: "Placid and Unoffensive, Buttery With A Hint Of Sauteed White Button Mushroom",
		img: "img/dairy/cheese/brie.webp",
		price: 42,
	},
	{
		id: "c60d7d8f481f47dfb6222a4f77a2e937",
		section: "dairy",
		type: "cheese",
		name: "Ricotta",
		desc: "Sweet, Fresh and Creamy",
		img: "img/dairy/cheese/ricotta.webp",
		price: 34,
	},{
		id: "y9e6485ca62440e490d7e3ad225060de",
		section: "dairy",
		type: "cheese",
		name: "Cream Cheese",
		desc: "Mild Sweet Taste With A Pleasant Slight Tang",
		img: "img/dairy/cheese/cream-cheese.webp",
		price: 30,
	},
	{
		id: "b1c7e5b71bc948f9bba5fdab5bea0544",
		section: "dairy",
		type: "cheese",
		name: "Gorgonzola",
		desc: "Full flavoured, Salty, and Earthy",
		img: "img/dairy/cheese/gorgonzola.webp",
		price: 40,
	},
	{
		id: "edc4d9c58cac4d15a0aa7c9d1cbc4815",
		section: "dairy",
		type: "cream",
		name: "Heavy Cream",
		desc: "30-36% fat",
		img: "img/dairy/cream/heavy-cream.webp",
		price: 36,
	},
	{
		id: "o3f76364fb4b4032a77e48a05171c2fe",
		section: "dairy",
		type: "cream",
		name: "Double Cream",
		desc: "43-48% fat",
		img: "img/dairy/cream/double-cream.webp",
		price: 38,
	},
	{
		id: "q44e019581334fbcb08bb23b03797dae",
		section: "dairy",
		type: "cream",
		name: "Clotted Cream",
		desc: "Higher fat Content than Double Cream",
		img: "img/dairy/cream/clotted-cream.webp",
		price: 40,
	},
	{
		id: "d553feca4091491da657f0915dec8804",
		section: "dairy",
		type: "cream",
		name: "Sour Cream",
		desc: "10-19% Fat, Lacto Balcillus Added For Tangy Taste",
		img: "img/dairy/cream/sour-cream.webp",
		price: 30,
	},
	{
		id: "u0b7ab3f12ad4ed4906ba7d7c8bee4b4",
		section: "dairy",
		type: "cream",
		name: "Creme Fraiche",
		desc: "38-48% Fat, Lacto Balcillus Added For Tangy Taste",
		img: "img/dairy/cream/creme-fraiche.webp",
		price: 39,
	},
	{
		id: "eaf2ea8800d440f5aa20d80d2a4bf5f4",
		section: "dairy",
		type: "cream",
		name: "Marscapone",
		desc: "70% Fat",
		img: "img/dairy/cream/marscapone.webp",
		price: 45,
	},
	{
		id: "118",
		section: "dairy",
		type: "cream",
		name: "Buttermilk",
		desc: "Liquid Which Remains when Cream Is Churned To Form Butter",
		img: "img/dairy/cream/buttermilk.webp",
		price: 28,
	},
	{
		id: "f9ce0173d444480aaf7b0ce6c5d8b523",
		section: "dairy",
		type: "ice-cream",
		name: "Confetti Cookie Gelato Layers",
		desc: "Vanilla Gelato, Vanilla Cookie Pieces, Pink Frosting, Rainbow Sprinkles",
		img: "img/dairy/ice-cream/confetti-cookie-gelato.webp",
		price: 110,
	},
	{
		id: "c278c05119124a19bc6753002cc8b22b",
		section: "dairy",
		type: "ice-cream",
		name: "Strawberry Shortcake Gelato Layers",
		desc: "Strawberry Shortcake, Shortbread Pieces, Tart Starwberry Rhubarb Sauce",
		img: "img/dairy/ice-cream/strawberry-shortcake-gelato.webp",
		price: 115,
	},
	{
		id: "a86a34f3e21047239c07afaca9345a96",
		section: "dairy",
		type: "ice-cream",
		name: "Cookies And Cream Gelato Layers",
		desc: "Cookies And Cream Gelato, Vanilla, Sweet Dulce De Leche, Pieces Of Chocolate Cookies, Cookie Crumbs",
		img: "img/dairy/ice-cream/cookies-and-cream-gelato.webp",
		price: 115,
	},
	{
		id: "d67eab10192f4d97bcc34e160d1f8dcb",
		section: "dairy",
		type: "ice-cream",
		name: "Chocolate Pretzel Gelato Layers",
		desc: "Salty Pretzel And Vanilla Gelato Bases, Crunchy Waffle Cone Pieces, Salted Pretzel Sauce",
		img: "img/dairy/ice-cream/chocolate-pretzel-gelato.webp",
		price: 120,
	},
	{
		id: "r4d7830aabfa4b42ad5bcef9c862807d",
		section: "dairy",
		type: "ice-cream",
		name: "Honey Graham Gelato",
		desc: "Creamy Vanilla Gelato, Sweet Wildflower Honey, Golden Graham Crackers",
		img: "img/dairy/ice-cream/honey-graham-gelato.webp",
		price: 120,
	},
	{
		id: "i6ac100bcad0460f9776d236f5c3193b",
		section: "dairy",
		type: "ice-cream",
		name: "Peanut Butter Vanilla Swirl Gelato",
		desc: "Vanilla Gelato, Creamy Roasted Peanut Butter Swirl, Mini Peanut Butter Cups",
		img: "img/dairy/ice-cream/vanilla-peanut-butter-swirl-gelato.webp",
		price: 120,
	},
	{
		id: "w969382b65c04dfdb2d8369015cc5967",
		section: "dairy",
		type: "milk",
		name: "Skim Milk",
		desc: "80 Calories, 0g Fat, 12g Carbs, 11g Sugar, 8g Protein",
		img: "img/dairy/milk/skim-milk.webp",
		price: 14,
	},
	{
		id: "cdd7a1f743ad439cb1b830686766f656",
		section: "dairy",
		type: "milk",
		name: "1% Milk",
		desc: "100 Calories, 2.5g Fat, 12g Carbs, 12g Sugar, 8g Protein",
		img: "img/dairy/milk/one-percent-milk.webp",
		price: 16,
	},
	{
		id: "g822be46f23349249e95317c51af52aa",
		section: "dairy",
		type: "milk",
		name: "2% Milk",
		desc: "120 Calories, 5g Fat, 12g Carbs, 12g Sugar, 8g Protein",
		img: "img/dairy/milk/two-percent-milk.webp",
		price: 18,
	},
	{
		id: "v60971b155514fd588301f6e768919d5",
		section: "dairy",
		type: "milk",
		name: "Whole Milk",
		desc: "150 Calories, 8g Fat, 12g Carbs, 12g Sugar, 8g Protein",
		img: "img/dairy/milk/whole-milk.webp",
		price: 18,
	},
	{
		id: "da379972f8694acda60965d131c07a0e",
		section: "dairy",
		type: "milk",
		name: "Soy Milk",
		desc: "110 Calories, 4.5g Fat, 9g Carbs, 6g Sugar, 8g Protein",
		img: "img/dairy/milk/soy-milk.webp",
		price: 18,
	},
	{
		id: "sf24f4be83f8405ab643da3ae2a830e6",
		section: "dairy",
		type: "milk",
		name: "Coconut Milk",
		desc: "70 Calories, 4.5g Fat, 6g Carbs, 5g Sugar, 0g Protein",
		img: "img/dairy/milk/coconut-milk.webp",
		price: 20,
	},
	{
		id: "te81480fda994acb9251f6ff5bc84379",
		section: "dairy",
		type: "milk",
		name: "Unsweetened Coconut Milk",
		desc: "40 Calories, 4g Fat, 1g Carbs, 0g Sugar, 0g Protein",
		img: "img/dairy/milk/unsweetened-coconut-milk.webp",
		price: 25,
	},
	{
		id: "a2ea3fa0f8444c319d5e4638085d09e9",
		section: "dairy",
		type: "milk",
		name: "Unsweetened Almond Milk",
		desc: "25 Calories, 2g Fat, 1g Carbs, 0g Sugar, 1g Protein",
		img: "img/dairy/milk/unsweetened-almond-milk.webp",
		price: 36,
	},
	{
		id: "d2df34adc0bd41ce87728435d4ab38eb",
		section: "dairy",
		type: "milk",
		name: "Sweetened Almond Milk",
		desc: "60 Calories, 2.5g Fat, 8g Carbs, 7g Sugar, 1g Protein",
		img: "img/dairy/milk/sweetened-almond-milk.webp",
		price: 30,
	},
	{
		id: "cb3d7ed285064946911c8e25a810a254",
		section: "dairy",
		type: "milk",
		name: "Oat Milk",
		desc: "100 Calories, 6g Fat, 11g Carbs, 8g Sugar, 2g Protein",
		img: "img/dairy/milk/oat-milk.webp",
		price: 38,
	},
	{
		id: "c907e2fca7724001a00ac9f78dcb138e",
		section: "dairy",
		type: "yogurt",
		name: "Plain Yogurt",
		desc: "Sour And Tart Taste",
		img: "img/dairy/yogurt/plain-yogurt.webp",
		price: 20,
	},
	{
		id: "d93f643df6ba40bbb857c5896ce6c5fb",
		section: "dairy",
		type: "yogurt",
		name: "Organic Plain Yogurt",
		desc: "Produced Using No GMOs, Sewage Sludge or Irradiation",
		img: "img/dairy/yogurt/organic-plain-yogurt.webp",
		price: 25,
	},
	{
		id: "f88553f7590b4b18a57508ea3a5da8d6",
		section: "dairy",
		type: "yogurt",
		name: "Whole Milk Yogurt",
		desc: "Made From Milk that Has All Its Components, Contains 4% Fat",
		img: "img/dairy/yogurt/whole-milk-yogurt.webp",
		price: 30,
	},
	{
		id: "b79c7d059dfe43bb8b190489d183f1e3",
		section: "dairy",
		type: "yogurt",
		name: "Probiotic Yogurt",
		desc: "Contains Streptococcus thermophilus and Lactobacillus bulgaricus",
		img: "img/dairy/yogurt/probiotic-yogurt.webp",
		price: 28,
	},
	{
		id: "ne8075231e6a4f61a0ed366e54e2a4b2",
		section: "dairy",
		type: "yogurt",
		name: "Greek Yogurt",
		desc: "More Protein, Less Sugar",
		img: "img/dairy/yogurt/greek-yogurt.webp",
		price: 29,
	},
	{
		id: "b390a88bb3ad4627b10901ca9da614a0",
		section: "dairy",
		type: "yogurt",
		name: "Cashewmilk Yogurt",
		desc: "Non-Dairy Yogurt Alternative Rich In Probiotic Goodness",
		img: "img/dairy/yogurt/cashewmilk-yogurt.webp",
		price: 35,
	},
	{
		id: "pa03474f90874616b2cdde51081792f0",
		section: "fresh",
		type: "fruit",
		name: "Granny Smith Apple",
		desc: "Apples And Pears",
		img: "img/fresh/fruit/apple.webp",
		price: 5,
	},
	{
		id: "w51fd9b4acde46a4a4998acba4e29aab",
		section: "fresh",
		type: "fruit",
		name: "Pear",
		desc: "Apples And Pears",
		img: "img/fresh/fruit/pear.webp",
		price: 6,
	},
	{
		id: "cb75f1bf79564cad94d6ef67c6060f56",
		section: "fresh",
		type: "fruit",
		name: "Orange",
		desc: "Citrus",
		img: "img/fresh/fruit/orange.webp",
		price: 6,
	},
	{
		id: "pd7388ca298b46c0a4000249fc461c52",
		section: "fresh",
		type: "fruit",
		name: "Grape Fruit",
		desc: "Citrus",
		img: "img/fresh/fruit/grapefruit.webp",
		price: 7,
	},
	{
		id: "v674b356a43d44f380fca7887560563c",
		section: "fresh",
		type: "fruit",
		name: "Mandarin",
		desc: "Citrus",
		img: "img/fresh/fruit/mandarin.webp",
		price: 4,
	},
	{
		id: "p476b1726a754b1d9efc098de171dd5e",
		section: "fresh",
		type: "fruit",
		name: "Banana",
		desc: "Tropical",
		img: "img/fresh/fruit/banana.webp",
		price: 8,
	},
	{
		id: "d8dff512e8eb4a4aa410b35a02b803f6",
		section: "fresh",
		type: "fruit",
		name: "Mango",
		desc: "Tropical",
		img: "img/fresh/fruit/mango.webp",
		price: 9,
	},
	{
		id: "cdc476f4f1e844b2bb0d2bd1e8ff7a16",
		section: "fresh",
		type: "fruit",
		name: "Starwberries",
		desc: "Berries",
		img: "img/fresh/fruit/strawberries.webp",
		price: 15,
	},
	{
		id: "p501d976f86c44adbd40e3e45cafbef1",
		section: "fresh",
		type: "fruit",
		name: "Blueberries",
		desc: "Berries",
		img: "img/fresh/fruit/blueberries.webp",
		price: 20,
	},
	{
		id: "a5b52afcbccc45c3853b620a7a672af8",
		section: "fresh",
		type: "fruit",
		name: "Kiwi Fruit",
		desc: "Berries",
		img: "img/fresh/fruit/kiwi-fruit.webp",
		price: 14,
	},
	{
		id: "q219f6b96473495f8e2848f83467b5a2",
		section: "fresh",
		type: "fruit",
		name: "Watermelon",
		desc: "Melons",
		img: "img/fresh/fruit/watermelon.webp",
		price: 25,
	},
	{
		id: "c4c8822173ec4765be0aa28c35337e26",
		section: "fresh",
		type: "fruit",
		name: "Plum",
		desc: "Stone Fruit",
		img: "img/fresh/fruit/plum.webp",
		price: 12,
	},
	{
		id: "a1809d32a3f94316ba9a1e66ebfb9fb5",
		section: "fresh",
		type: "herbs",
		name: "Sage",
		desc: "Works Well With Pork, Bean, Potato, And Cheese Dishes",
		img: "img/fresh/herbs/sage.webp",
		price: 20,
	},
	{
		id: "kf6316c162f44a1e87e98f074b9ff842",
		section: "fresh",
		type: "herbs",
		name: "Thyme",
		desc: "WorkS Well With Any Kind Of Meat, Poultry, Fish, And Vegetable Dishes",
		img: "img/fresh/herbs/thyme.webp",
		price: 20,
	},
	{
		id: "p63f89b175fd49f4a3628210eed0b12c",
		section: "fresh",
		type: "herbs",
		name: "Dill",
		desc: "Works Well With Fish And Shellfish",
		img: "img/fresh/herbs/dill.webp",
		price: 20,
	},
	{
		id: "c56c28941db74a1fb844ddd1e50e3bd8",
		section: "fresh",
		type: "herbs",
		name: "Rosemary",
		desc: "Soups, Meats, Stews, And Sauces",
		img: "img/fresh/herbs/rosemary.webp",
		price: 20,
	},
	{
		id: "ff973d9f3f884418b52904017d94b882",
		section: "fresh",
		type: "herbs",
		name: "Basil",
		desc: "Works Well With Tomatoes, Any Type Of Meat Or Seafood",
		img: "img/fresh/herbs/basil.webp",
		price: 20,
	},
	{
		id: "e294a0a5e185411bbf489ea99d56b780",
		section: "fresh",
		type: "herbs",
		name: "Mint",
		desc: "Works Well With Summer fresh Salads",
		img: "img/fresh/herbs/mint.webp",
		price: 20,
	},
	{
		id: "p7e93b90a43f41059c2ddaaa6b4e26af",
		section: "fresh",
		type: "herbs",
		name: "Chives",
		desc: "Works Well As A Garnish  For Salads",
		img: "img/fresh/herbs/chives.webp",
		price: 20,
	},
	{
		id: "e92d2e73d99f444d84482e7107200823",
		section: "fresh",
		type: "herbs",
		name: "Parsley",
		desc: "Works Well In Sauces, Salads, And As A Garnish",
		img: "img/fresh/herbs/parsley.webp",
		price: 20,
	},
	{
		id: "ef2755baf0044c4bab80e7a466fb9db7",
		section: "fresh",
		type: "herbs",
		name: "Oregano",
		desc: "Works Well In Mediterranean And Mexican Dishes",
		img: "img/fresh/herbs/oregano.webp",
		price: 20,
	},
	{
		id: "b5b7f7cc95994df894d6dcf35201a8b3",
		section: "fresh",
		type: "vegetables",
		name: "Lettuce",
		desc: "Leafy Green Vegetable",
		img: "img/fresh/vegetables/lettuce.webp",
		price: 15,
	},
	{
		id: "r01df32980794e33b22d58ceccff8821",
		section: "fresh",
		type: "vegetables",
		name: "Spinach",
		desc: "Leafy Green Vegetable",
		img: "img/fresh/vegetables/spinach.webp",
		price: 16,
	},
	{
		id: "qeb1eef4f14e4c0180962f7db2223777",
		section: "fresh",
		type: "vegetables",
		name: "Cabbage",
		desc: "Cruciferous Vegetable",
		img: "img/fresh/vegetables/cabbage.webp",
		price: 12,
	},
	{
		id: "b0fc09363a5c4f868a535a51e991e807",
		section: "fresh",
		type: "vegetables",
		name: "Garlic",
		desc: "Allium Vegetable",
		img: "img/fresh/vegetables/garlic.webp",
		price: 17,
	},
	{
		id: "v25c353f6c8740489801f2c8d0dfb035",
		section: "fresh",
		type: "vegetables",
		name: "Pumpkin",
		desc: "Marrow Vegetable",
		img: "img/fresh/vegetables/pumpkin.webp",
		price: 25,
	},
	{
		id: "cc4b2f1d16f547628a362989ad789ccb",
		section: "fresh",
		type: "vegetables",
		name: "Cucumber",
		desc: "Marrow Vegetable",
		img: "img/fresh/vegetables/cucumber.webp",
		price: 17,
	},
	{
		id: "ab4ef492dde742abae9163e0b5fd7ec1",
		section: "fresh",
		type: "vegetables",
		name: "Zucchini",
		desc: "Marrow Vegetable",
		img: "img/fresh/vegetables/zucchini.webp",
		price: 18,
	},
	{
		id: "u172b15f2fad43bcb4a6e4e82a89378f",
		section: "fresh",
		type: "vegetables",
		name: "Potato",
		desc: "Root Vegetable",
		img: "img/fresh/vegetables/potato.webp",
		price: 19,
	},
	{
		id: "pf9e72e7b7e14753863a0fe97979d5ea",
		section: "fresh",
		type: "vegetables",
		name: "Asparagus",
		desc: "Plant Stem Vegetable",
		img: "img/fresh/vegetables/asparagus.webp",
		price: 20,
	},
	{
		id: "af756d56962f485fa75ba53bd73a2373",
		section: "fresh",
		type: "vegetables",
		name: "Celery",
		desc: "Plant Stem Vegetable",
		img: "img/fresh/vegetables/celery.webp",
		price: 22,
	},
	{
		id: "uc4a4ea4fdbb476dbc2a668e14d533e1",
		section: "fresh",
		type: "vegetables",
		name: "Onion",
		desc: "Allium Vegetable",
		img: "img/fresh/vegetables/onion.webp",
		price: 16,
	},
	{
		id: "a56e57d5194c4b0a9948651fce60c7fe",
		section: "frozen",
		type: "meals",
		name: "Lasagne",
		desc: "Made With Fresh Hand-Rolled Pasta Sheets, Beef Ragu And Bechamel Sauce",
		img: "img/frozen/meals/lasagne.webp",
		price: 68,
	},
	{
		id: "f45ecd9a7dcf49178ff78f49bbd94fae",
		section: "frozen",
		type: "meals",
		name: "Cannelloni",
		desc: "Fresh Pasta Rolls Filled With Nutmeg-Rich Spinach, Topped With White Sauce, Tangy Tomato And Basil Sauce, And fresh Ricotta Cheese",
		img: "img/frozen/meals/cannelloni.webp",
		price: 75,
	},
	{
		id: "be2b9dbe6e17452c84100fdb340e0e3c",
		section: "frozen",
		type: "meals",
		name: "Pizza",
		desc: "Feta, Fresh Local Spinach And Sun Dried Tomato Top The Neapolitan-Style Wood Fire Base",
		img: "img/frozen/meals/pizza.webp",
		price: 90,
	},
	{
		id: "cebdcd5c921d4f2d9c9f44c3d4df078e",
		section: "frozen",
		type: "meals",
		name: "Thai Green Curry",
		desc: "Green Coconut Curry Filled With Chicken Breast Pieces, Bamboo Shoots And Green Beans",
		img: "img/frozen/meals/thai-green-curry.webp",
		price: 80,
	},
	{
		id: "ffc1712211d1476f974bf8ed40cd5c88",
		section: "frozen",
		type: "meals",
		name: "Rice & Lentil Pilaf",
		desc: "Basmatic Rice, Brown Lentils, Warming Spices, And Crispy Fried Onions",
		img: "img/frozen/meals/rice-and-lentil-pilaf.webp",
		price: 35,
	},
	{
		id: "xf1aadcd940d41dbb38058f5541abec6",
		section: "frozen",
		type: "meals",
		name: "Chicken Cacciatore",
		desc: "Italian Huntsman's Stew, With Olives, Sundried Tomato And Sauteed Mushrooms Served With Poppy Seed Sweet Potato Mash",
		img: "img/frozen/meals/chicken-cacciatore.webp",
		price: 78,
	},
	{
		id: "b5fe40e3811c4eb4a8196b05b14633ab",
		section: "frozen",
		type: "meals",
		name: "Butter Chicken",
		desc: "Chicken Breast In Spiced And Decadently Creamy Butter Sauce",
		img: "img/frozen/meals/butter-chicken.webp",
		price: 75,
	},
	{
		id: "t29be91d32d745bca5f17ddb0ce738c5",
		section: "frozen",
		type: "meals",
		name: "Meatballs Alla Napoletana",
		desc: "Juicy meatballs In A Tasty Napoletana Sauce",
		img: "img/frozen/meals/meatballs-alla-napoletana.webp",
		price: 80,
	},
	{
		id: "n0f5aaf653f24a0ea14bcfa0c715dc2f",
		section: "frozen",
		type: "meats",
		name: "Chicken Strips",
		desc: "Southern Fried Chicken Strips 400g",
		img: "img/frozen/meats/chicken-strips.webp",
		price: 55,
	},
	{
		id: "bbdfa1d80877470dad389dc297ec814d",
		section: "frozen",
		type: "meats",
		name: "Chicken Steaklets",
		desc: "Lime And Herb Chicken Steaklets 400g",
		img: "img/frozen/meats/chicken-steaklets.webp",
		price: 53,
	},
	{
		id: "nc32b295e0214ec7abdecf6d3b88eb66",
		section: "frozen",
		type: "meats",
		name: "Beef Burgers",
		desc: "Beef Patties 800g",
		img: "img/frozen/meats/beef-burgers.webp",
		price: 80,
	},
	{
		id: "adf6ef604770413094212991e93b16df",
		section: "frozen",
		type: "meats",
		name: "Pork Ribs",
		desc: "St. Louis Style Pork Belly Ribs 700g",
		img: "img/frozen/meats/pork-ribs.webp",
		price: 153,
	},
	{
		id: "fb221b70e55d42c1b5eac952fdb79a12",
		section: "frozen",
		type: "meats",
		name: "Beef Ribs",
		desc: "Premium Cut Beef Ribs 1kg",
		img: "img/frozen/meats/beef-ribs.webp",
		price: 220,
	},
	{
		id: "p2e35f6196e44cddaa305a6e3db9b2f9",
		section: "frozen",
		type: "meats",
		name: "Chicken Burgers",
		desc: "Cheese Flavoured Crumbed Chicken Patties 520g",
		img: "img/frozen/meats/chicken-burgers.webp",
		price: 60,
	},
	{
		id: "ea9a0487f0b74063b84b5675e6c90452",
		section: "frozen",
		type: "seafood",
		name: "Fish Fingers",
		desc: "Crispy Frozen Fish Fingers 600g",
		img: "img/frozen/seafood/frozen-fish-fingers.webp",
		price: 59,
	},
	{
		id: "ba0743b7cfb147a1b072de0fc5b1d72f",
		section: "frozen",
		type: "seafood",
		name: "Hake Fillet",
		desc: "Ciabatta Crumbed hake Portions 400g",
		img: "img/frozen/seafood/frozen-hake-fillets.webp",
		price: 65,
	},
	{
		id: "j862736b4fd346b29b10c99017310698",
		section: "frozen",
		type: "seafood",
		name: "Mussels",
		desc: "Froze Cooked Whole West Coast Mussels 455g",
		img: "img/frozen/seafood/frozen-mussels.webp",
		price: 45,
	},
	{
		id: "b1eba0b8707a4b36b46289ebca1df1ec",
		section: "frozen",
		type: "seafood",
		name: "Seafood Mix",
		desc: "Frozen Seafood Mix 700g",
		img: "img/frozen/seafood/frozen-seafood-mix.webp",
		price: 75,
	},
	{
		id: "va530700cc134f99b1b8e5ac7b2008f7",
		section: "frozen",
		type: "seafood",
		name: "Prawns",
		desc: "Frozen Prawn Meat 800g",
		img: "img/frozen/seafood/frozen-prawns.webp",
		price: 190,
	},
	{
		id: "fcde167910a74de3ba951a16c85ab59e",
		section: "frozen",
		type: "seafood",
		name: "Calamari",
		desc: "Frozen Calamari Heads And Tentacles 400g",
		img: "img/frozen/seafood/frozen-calamari.webp",
		price: 80,
	},
	{
		id: "a9e81c6ac4ab4174969424128f32149d",
		section: "frozen",
		type: "seafood",
		name: "Seafood Paella",
		desc: "Frozen Seafood Paella 500g",
		img: "img/frozen/seafood/frozen-paella.webp",
		price: 92,
	},
	{
		id: "d79cd87e5796471a8748d8070923d564",
		section: "frozen",
		type: "seafood",
		name: "Oysters",
		desc: "Frozen Pacific half Shell Oysters 200g",
		img: "img/frozen/seafood/frozen-oysters.webp",
		price: 130,
	},
	{
		id: "g2d42246fe554212a754eab2cfe296dc",
		section: "frozen",
		type: "greens",
		name: "Cherries",
		desc: "Frozen Dark Sweet Cherries 400g",
		img: "img/frozen/greens/frozen-cherries.webp",
		price: 50,
	},
	{
		id: "u2816e6b5c704a93a99d268aa744f1ff",
		section: "frozen",
		type: "greens",
		name: "Berries",
		desc: "Frozen Organic Berries 1.36kg",
		img: "img/frozen/greens/frozen-berries.webp",
		price: 42,
	},
	{
		id: "pa85890ca7ba411ab7e4b9b15644f870",
		section: "frozen",
		type: "greens",
		name: "Speciality Fruits",
		desc: "Frozen Dragon Fruit, Mangoes, Strawberries, Peaches 1kg",
		img: "img/frozen/greens/frozen-speciality-fruit.webp",
		price: 60,
	},
	{
		id: "ac1824be091c44e0b851ec8fa14fed93",
		section: "frozen",
		type: "greens",
		name: "Edamame",
		desc: "Frozen Edamame 500g",
		img: "img/frozen/greens/frozen-edamame.webp",
		price: 36,
	},
	{
		id: "bda31766e2ed48a593e4a21f834bd6cd",
		section: "frozen",
		type: "greens",
		name: "Broccoli",
		desc: "Frozen Broccoli 400g",
		img: "img/frozen/greens/frozen-broccoli.webp",
		price: 30,
	},
	{
		id: "oefe11f4503b43289f564fcbc3bd0840",
		section: "frozen",
		type: "greens",
		name: "Cauliflower",
		desc: "Frozen Riced Cauliflower 500g",
		img: "img/frozen/greens/frozen-cauliflower.webp",
		price: 39,
	},
	{
		id: "i20d7ff0b67c40e9a71fd25c11012a8c",
		section: "frozen",
		type: "potatoes",
		name: "Crinkles",
		desc: "Frozen French Fried Crinkled Potatoes 1kg",
		img: "img/frozen/potatoes/frozen-frenchfries.webp",
		price: 45,
	},
	{
		id: "p2197308ff5142928ba7f334c80a7f97",
		section: "frozen",
		type: "potatoes",
		name: "Tater Tots",
		desc: "Frozen Seasoned Shedded Potatoes 1kg",
		img: "img/frozen/potatoes/frozen-tatertots.webp",
		price: 43,
	},
	{
		id: "u2bc63f8f5094c83abc32116d5e922e1",
		section: "frozen",
		type: "potatoes",
		name: "Hash Brown",
		desc: "Frozen Shredded Hash Brown Potatoes 1kg",
		img: "img/frozen/potatoes/frozen-hashbrowns.webp",
		price: 40,
	},
	{
		id: "ce60fa1a7bcc43f89f8cea7fec0040a2",
		section: "frozen",
		type: "potatoes",
		name: "Mashed Potatoes",
		desc: "Frozen Creamy Mashed Potatoes 500g",
		img: "img/frozen/potatoes/frozen-mashedpotatoes.webp",
		price: 30,
	},
	{
		id: "aa6efc04c4e0487db72b21fa08b9858b",
		section: "seafood",
		type: "fish",
		name: "Tuna Steaks",
		desc: "Fresh Yellowfin Tuna Steaks 800g",
		img: "img/seafood/fish/tuna-steak.webp",
		price: 349,
	},
	{
		id: "bf482ce7cd0c499db71a33ef076599ea",
		section: "seafood",
		type: "fish",
		name: "Swordfish Steaks",
		desc: "Fresh Swordfish Steaks 800g",
		img: "img/seafood/fish/swordfish-steaks.webp",
		price: 269,
	},
	{
		id: "cf02619291944b95a0aad9ccfef34edd",
		section: "seafood",
		type: "fish",
		name: "Sailfish Steaks",
		desc: "Fresh Sailfish Steaks 800g",
		img: "img/seafood/fish/sailfish-steaks.webp",
		price: 259,
	},
	{
		id: "ldbc9ea34920492f87aacf9d40752169",
		section: "seafood",
		type: "fish",
		name: "Salmon Fillets",
		desc: "Fresh Cape Salmon Fillets/Geelbek 1200g",
		img: "img/seafood/fish/salmon-fillets.webp",
		price: 400,
	},
	{
		id: "ed9cdaa1c0a74aaa959d4d93cfcaf1b8",
		section: "seafood",
		type: "fish",
		name: "Angel Fish Fillets",
		desc: "Fresh Angel Fish Fillets 1100g",
		img: "img/seafood/fish/angelfish-fillets.webp",
		price: 219,
	},
	{
		id: "vdfc4975a05e4048afd20ffa5d0feb86",
		section: "seafood",
		type: "fish",
		name: "Hake Fillets",
		desc: "Fresh Hake/ Stock Fish Fillets 1.6kg",
		img: "img/seafood/fish/hake-fillets.webp",
		price: 219,
	},
	{
		id: "f8a482df63cc4e34b6902c0795841cfc",
		section: "seafood",
		type: "fish",
		name: "Kingklip Fillets",
		desc: "Fresh Kingklip Fillets 1100g",
		img: "img/seafood/fish/kingklip-fillets.webp",
		price: 329,
	},
	{
		id: "efedad6772344fbd9dd258d6035e7182",
		section: "seafood",
		type: "fish",
		name: "Yellowtail Fillets",
		desc: "Fresh Yellowtail Fillets 1800g",
		img: "img/seafood/fish/yellowtail-fillets.webp",
		price: 399,
	},
	{
		id: "cdc904e5688d4b8fa38815ae4036b293",
		section: "seafood",
		type: "roe",
		name: "Tobiko",
		desc: "Roe From Flying Fish Species 50g",
		img: "img/seafood/roe/tobiko.webp",
		price: 500,
	},
	{
		id: "r06cb713c2c94cdb9c96ac9ec19a2d86",
		section: "seafood",
		type: "roe",
		name: "Masago",
		desc: "Roe From The Capelin(Smelt Family) 50g",
		img: "img/seafood/roe/masago.webp",
		price: 600,
	},
	{
		id: "p9e675c899b54b87af157dfbb639475d",
		section: "seafood",
		type: "roe",
		name: "Ikura",
		desc: "Salmon Roe 50g",
		img: "img/seafood/roe/ikura.webp",
		price: 350,
	},
	{
		id: "ebc5148aa2084419ae9b90c181666949",
		section: "seafood",
		type: "roe",
		name: "Caviar",
		desc: "Roe Of The Wild Sturgeon Fish 50g",
		img: "img/seafood/roe/caviar.webp",
		price: 1000,
	},
	{
		id: "cde8a6d30b7f4a8898699d76c08b5b04",
		section: "seafood",
		type: "shellfish",
		name: "Oysters",
		desc: "12 Large Fresh Oysters",
		img: "img/seafood/shellfish/fresh-oysters.webp",
		price: 229,
	},
	{
		id: "t0861f69a8234660b9bf2038414d5dff",
		section: "seafood",
		type: "shellfish",
		name: "Crayfish",
		desc: "8 Fresh Large Crayfish",
		img: "img/seafood/shellfish/fresh-crayfish.webp",
		price: 1649,
	},
	{
		id: "v537733f63164e46a208ad9cb66adbf4",
		section: "seafood",
		type: "shellfish",
		name: "Tiger Prawns",
		desc: "2 Fresh Giant Tiger Prawns",
		img: "img/seafood/shellfish/fresh-tiger-prawns.webp",
		price: 549,
	},
	{
		id: "b0d8685a111147cb8b2c2cee5360174a",
		section: "seafood",
		type: "shellfish",
		name: "Mussels",
		desc: "Half Shell Black Mussels 1600g",
		img: "img/seafood/shellfish/fresh-mussels.webp",
		price: 329,
	},
	{
		id: "c7567c21a8754430beac99e2d9b39710",
		section: "seafood",
		type: "shellfish",
		name: "Clams",
		desc: "Fresh Hand Picked Clams 2kg",
		img: "img/seafood/shellfish/fresh-clams.webp",
		price: 229,
	},
	{
		id: "f272c14e18b942ff9886ba11247057e9",
		section: "vegan",
		type: "meals",
		name: "Chickpea Curry",
		desc: "Sweet Potato, Chickpeas, Spinach And Garlic in Light Curry Sauce",
		img: "img/vegan/meals/vegan-sweet-potato-chickpea-curry.webp",
		price: 70,
	},
	{
		id: "p75430cb26f34d07894e79e98b4ab8f4",
		section: "vegan",
		type: "meals",
		name: "Beans And Quinoa Salad",
		desc: "Four Beans Fried In Olive Oil And Lemon Juice Served With Quinoa",
		img: "img/vegan/meals/vegan-bean-quinoa-salad.webp",
		price: 70,
	},
	{
		id: "p9dfb34ac886429197d4cdc14dc47561",
		section: "vegan",
		type: "meals",
		name: "Pasta Salad",
		desc: "Fusilli Pasta, Rocket, Red Onion, Cherry Tomatoes, Cucumber, And mixed Peppers Served With Mediterranean dressing Dressing",
		img: "img/vegan/meals/vegan-pasta-salad.webp",
		price: 70,
	},
	{
		id: "n0a2e2a2ac9f4a0a9218fda75fd4b659",
		section: "vegan",
		type: "meals",
		name: "Cauliflower and Cous Cous",
		desc: "Cauliflower Ends On A Bed Of Cous Cous With Roasted Peppers And Garlic, Served With A light Vinaigrette",
		img: "img/vegan/meals/vegan-cauliflower-couscous.webp",
		price: 70,
	},
	{
		id: "m853e434d0d94911b82f845303e230be",
		section: "vegan",
		type: "meals",
		name: "Napoletana Pasta",
		desc: "Fusilli Pasta In A Tomato, Onion, Garlic, And Basil Sauce",
		img: "img/vegan/meals/vegan-napoletana-pasta.webp",
		price: 70,
	},
	{
		id: "y8df3daed1564bef84a38a2dc8692c2e",
		section: "vegan",
		type: "meals",
		name: "Pumpkin And Lentil Curry",
		desc: "Cinnamon Roasted Pumpkin And lentils In A Light Curry Sauce With Rocket And Thyme Leaves",
		img: "img/vegan/meals/vegan-pumpkin-lentil-curry.webp",
		price: 70,
	},
	{
		id: "p5c4e8b9f347444499f4ae1a67ce6d0e",
		section: "vegan",
		type: "snacks",
		name: "Peanut Butter Cups",
		desc: "Dark Chocolate Peanut Butter Cups",
		img: "img/vegan/snacks/vegan-dark-chocolate-cups.webp",
		price: 20,
	},
	{
		id: "ae73d2e162744379b130720a4ceb0003",
		section: "vegan",
		type: "snacks",
		name: "Hot Curls",
		desc: "Cruchy Hot Curls, Fiery Hot",
		img: "img/vegan/snacks/vegan-hot-curls.webp",
		price: 25,
	},
	{
		id: "n9172c56d0e2469d8902eba297726b33",
		section: "vegan",
		type: "snacks",
		name: "Roasted Chickpeas",
		desc: "Sea Salt Flavoured Roasted Chickpeas",
		img: "img/vegan/snacks/vegan-roasted-chickpea.webp",
		price: 45,
	},
	{
		id: "v3747bef88be470bb38e4978d0403162",
		section: "vegan",
		type: "snacks",
		name: "Mushroom Jerky",
		desc: "Sesame, Ginger, And Korean Chili Portabella Mushroom Jerky",
		img: "img/vegan/snacks/vegan-mushroom-jerky.webp",
		price: 18,
	},
	{
		id: "m376c5145df4416e85d6744ab28709b7",
		section: "vegan",
		type: "snacks",
		name: "Cookie Dough Chunks",
		desc: "Vegan Chocolate Chip Cookie Dough Chunks",
		img: "img/vegan/snacks/vegan-cookie-dough-chunks.webp",
		price: 15,
	},
	{
		id: "e5ceaef0b426496e89c2992b1a30b440",
		section: "vegan",
		type: "snacks",
		name: "Artisan Peanuts",
		desc: "Pizootz Flavour Infused Virginia Artisan Peanuts",
		img: "img/vegan/snacks/vegan-artisan-peanuts.webp",
		price: 19,
	},
	{
		id: "d3cfe4a8ca6d4b238181d9781fbd3dbf",
		section: "vegan",
		type: "snacks",
		name: "Breakfast Biscuits",
		desc: "Blueberry Breakfast Biscuits",
		img: "img/vegan/snacks/vegan-breakfast-biscuits.webp",
		price: 30,
	},
	{
		id: "g3647af76e974ed29a415b760ad6dcc0",
		section: "vegan",
		type: "snacks",
		name: "Cookies",
		desc: "Double Chocolate Chip Cookies",
		img: "img/vegan/snacks/vegan-cookies.webp",
		price: 36,
	},
	{
		id: "c0eb45e0de11470bb0ff9a19892a3159",
		section: "vegan",
		type: "dips",
		name: "Queso Blanco",
		desc: "Spicy Queso Blanco Style Dip",
		img: "img/vegan/dips/queso-blanco.webp",
		price: 40,
	},
	{
		id: "vcd8037b5f8b4fdb9c76a241a8dbb651",
		section: "vegan",
		type: "dips",
		name: "Tzatziki",
		desc: "Plant Based Tzatziki Style Dip",
		img: "img/vegan/dips/tzatziki.webp",
		price: 40,
	},
	{
		id: "xaf06745a1ef4d8b921ed9d7da6487ac",
		section: "vegan",
		type: "dips",
		name: "Cilantro",
		desc: "Plant Based Cilantro Dip",
		img: "img/vegan/dips/cilantro.webp",
		price: 40,
	},
	{
		id: "vb593e6430a645c494d8d405e39dfd06",
		section: "vegan",
		type: "dips",
		name: "Buffalo",
		desc: "Plant Based Buffalo style Dip",
		img: "img/vegan/dips/buffalo.webp",
		price: 40,
	},
	{
		id: "yf73f5036d75449795e6a0e5ff33e67a",
		section: "vegan",
		type: "dips",
		name: "Queso",
		desc: "Plant Based Queso Style Dip",
		img: "img/vegan/dips/queso.webp",
		price: 40,
	},
	{
		id: "q3890d4b6e174a6a980e2baf57c042c8",
		section: "vegan",
		type: "dips",
		name: "Avocado",
		desc: "Avacado And Jalapeno Salsa",
		img: "img/vegan/dips/avocado.webp",
		price: 40,
	},
	{
		id: "n1588daef00c48dea33df25165046c28",
		section: "wine",
		type: "red",
		name: "Beyerskloof Pinotage",
		desc: "Beautifully Balanced With Strong Dark Fruit Flavours, Some Herbs And A Dash Of Smokiness",
		img: "img/wine/red/beyerskloof-pinotage.webp",
		price: 95,
	},
	{
		id: "d7587feca2bb42d8af00ebdd2621a9f9",
		section: "wine",
		type: "red",
		name: "Protea Cabernet Sauvignon",
		desc: "A Dark And Spicy Cabernet Sauvignon, This Fine Red Wine Is Full-Bodied And Dry",
		img: "img/wine/red/protea.webp",
		price: 80,
	},
	{
		id: "c572fd6b611744e0b2587fd7a291341d",
		section: "wine",
		type: "red",
		name: "Franschhoek Cellar The Old Museum Merlot",
		desc: "This Delicious Merlot Has A Wonderful Plum Colour, Herbal Nuances And Plum Aromas",
		img: "img/wine/red/franschoek-merlot.webp",
		price: 85,
	},
	{
		id: "uf482dc024e44185a6eecc0064b4dc5d",
		section: "wine",
		type: "red",
		name: "Franschhoek Cellar Baker Station Shiraz",
		desc: "A South African Syrah That Has A Spicy Kick. This Wine Pairs Well With Blue Cheese, Cinnamon And Beef And Lamb Dishes",
		img: "img/wine/red/franschoek-shiraz.webp",
		price: 85,
	},
	{
		id: "ff15bb64c1994ab19bc29dc6ca6c640f",
		section: "wine",
		type: "red",
		name: "Ken Forrester Petit Pinotage",
		desc: "This Cheerfully Petit Pinotage Reflects The Modern Fruit Driven Wine Style",
		img: "img/wine/red/petit-pinotage.webp",
		price: 70,
	},
	{
		id: "padebd004d2c4454ae446453d49c9b32",
		section: "wine",
		type: "white",
		name: "Diemersdal Sauvignon Blanc",
		desc: "Ripe Fruit Purity With A Lingering Fruity After Taste",
		img: "img/wine/white/diemersdal.webp",
		price: 90,
	},
	{
		id: "w0f6a76b0c9440afaddc4f3329891635",
		section: "wine",
		type: "white",
		name: "Ken Forrester Petit Chenin Blanc",
		desc: "Can Be Served With Lightly Spiced Food, Shellfish And Cheese Platters",
		img: "img/wine/white/ken-forrester.webp",
		price: 65,
	},
	{
		id: "v91b704f477643bab446975597d982fd",
		section: "wine",
		type: "white",
		name: "Oakridge Chardonnay",
		desc: "Dry White, This Chardonnay Is Medium-Bodied With Well-Balanced Acidity",
		img: "img/wine/white/oakridge.webp",
		price: 38,
	},
	{
		id: "n950ee454a50459e8c87159b04af303e",
		section: "wine",
		type: "rose",
		name: "Drostdy Hof Natural Sweet",
		desc: "A Light And Fruity Wine With Fresh Strawberry, Cherry, And Plum Notes",
		img: "img/wine/rose/drostdy-hof.webp",
		price: 43,
	},
	{
		id: "f451ee7639824e9187c3722df4ea3255",
		section: "wine",
		type: "rose",
		name: "Protea Rosé",
		desc: "Pairs Well With Seafood, Especially White Fish like Sole",
		img: "img/wine/rose/protea-rose.webp",
		price: 80,
	},
	{
		id: "i50dff01180b4da19cae5ea68758fcc2",
		section: "wine",
		type: "rose",
		name: "Warwick The First Lady Dry Rosé",
		desc: "Bone Dry Rosé With Amazing Aromatics",
		img: "img/wine/rose/warwick.webp",
		price: 100,
	},
];









